alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"
alias ll="ls -lh"
alias la="ll -a"
alias cd..="cd .."
alias dc="cd"
alias netstat_osx="sudo lsof -i -P"
alias gut="gti"
alias fuckingdoit='sudo $(history -p !-1)'
alias nojrebel="export MAVEN_OPTS=\"$NOJREBEL_OPTS\""
alias withjrebel="export MAVEN_OPTS=\"$JREBEL_OPTS\""
alias mvndbg='MAVEN_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=1044" mvn'
alias mvn="mvn-color"
alias startpostgres="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start"
alias whatismyip="curl -s ifconfig.me/ip"
alias rebasemess="git reset --hard && git checkout master && git rebase --abort"
alias upgrade="sudo apt-get update && sudo apt-get upgrade"
alias vssh="vagrant ssh"
alias vupssh="vagrant up && vagrant ssh"
alias fup="fig up -d && fig logs"
alias doims="docker images | head"
